name: Build site on schedule or main branch update

on:
  push:
    branches:
      - main
    # CAUTION
    # Risk of infinite workflow loop if the watched files
    # are changed by the workflow itself
    paths:
      - "osmosfeed.yaml"
      - "package.json"
  schedule:
    # Adjust refresh schedule here. By default, it runs once per day.
    # Syntax reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    # Recommended tool: https://crontab.guru/
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm i
      - run: npm run build
        env:
          # The token allows build script to read repo metadata via github API
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config --global user.email "no-reply@osmosfeed.org"
          git config --global user.name "osmosfeed bot"
          git add -A
          git commit -m "Workflow update"
          git push
